### ISSUE TITLE
如何使用16号字体

### ISSUE THREAD

**Issue by youxinweizhi** [JeremyHash/EinkBook-LuatOS#1]
如何使用16号字体

**Comment by JeremyHash** [comment]
在LuatOS-ESP32仓库中寻找`components\luat\include\luat_conf_bsp.h`配置文件，打开`#define USE_U8G2_OPPOSANSM16_CHINESE`宏，然后重新编译LuatOS-ESP32的固件

但是使用16号字体的话，由于字体变大，页面布局会发生变化，所以还需要对客户端Lua代码和服务端分页代码稍作修改才能合理显示

编译LuatOS-ESP32的操作，可以在这里找到 https://wiki.luatos.com/develop/compile/ESP32C3.html
